### ISSUE TITLE
As a user, I want to use CSV files, so that I can easily integrate my existing systems.

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#21]
### Acceptance Criteria

Upon adding a CSV file to '/prepare' it is automatically:

- [ ] transformed into Parquet
- [ ] saved to '/load'
- [ ] deleted from '/prepare' 

### Tasks

- [ ] Stream reader to parse CSV by line from S3
- [ ] Interpolate schema
