### ISSUE TITLE
As a user, I want to use Avro files, so that I can easily integrate my existing systems.

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#22]
### Acceptance Criteria

Upon adding an Avro file to '/prepare' it is automatically:

- [ ] transformed into Parquet
- [ ] saved to '/load'
- [ ] deleted from '/prepare' 

### Tasks

- [ ] Stream reader to parse Avro by line from S3
- [ ] Interpolate schema
