### ISSUE TITLE
As a user, I want to use ORC files, so that I can easily integrate my existing systems.

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#23]
### Acceptance Criteria

Upon adding an ORC file to '/prepare' it is automatically:

- [ ] transformed into Parquet
- [ ] saved to '/load'
- [ ] deleted from '/prepare' 

### Tasks

- [ ] Stream reader to parse ORC by line from S3
- [ ] Interpolate schema
