### ISSUE TITLE
As a user, I want to use Parquet files, so that I can easily integrate my existing systems.

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#24]
### Acceptance Criteria

Upon adding a Parquet file to '/prepare' it is automatically:

- [ ] copied to '/load'
- [ ] deleted from '/prepare' 

_NOTE: this is simply to protect against devs dropping files in the wrong spot_

### Tasks

- [ ] skip reading and parsing
