### ISSUE TITLE
As a developer, I want to create a reusable parquet translator, so that I can support numerous file types.

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#25]
### Acceptance Criteria

- [ ] A single entry point that depending on filetype can read, translate, and then write the result 

### Tasks

- [ ] An extendable reader interface to parse data files in batches
- [ ] A schema interpolation method that can figure out what type fields are 
- [ ] A stream writer method to write to an s3 `/tmp` bucket  

### Relates to

- [x] #21 
- [x] #22
- [x] #23 
- [ ] #24
