### ISSUE TITLE
As a developer, I want a single entry point, so that I can deploy to a serverless function.

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#26]
### Acceptance Criteria

- [ ] A single entry point for reading, translating, and then moving files from `/prepare` to `/load`

### Tasks

- [ ] A single entry point that accepts an S3 event bridge notification from SQS
- [ ] Calls #25 
- [ ] Copies results of #25 to `/load` and deletes the `/tmp` file
