### ISSUE TITLE
As a user, I want a trash folder, so that I can debug file issues before deletion

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#27]
### Acceptance Criteria

- [ ] files scheduled for deletion reside in a `trash` folder for 14 days
- [ ] after 14 days the files are removed from the bucket

### Tasks

- [ ] s3 lifecycle set up for `/trash` key to auto expire after 14 days
- [ ] change all delete calls to move to `/trash`

**Comment by mike-audi** [comment]
closed in #29
