### ISSUE TITLE
As a customer, I want only a single load balancer for my cluster traffic

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#54]
### Acceptance Criteria

- [ ] a single application load balancer to handle both http and grpc traffic
- [ ] lower monthly bill per deployment

### Tasks

- [ ] remove the NLB
- [ ] update the ALB listeners
- [ ] update the task definitions
- [ ] update the security groups

**Comment by mike-audi** [comment]
closed in #99
