### ISSUE TITLE
As a user, I want all logs aggregated in iceberg, so that I can search them.

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#72]
### Acceptance Criteria

- [ ] collect error logs from cloud watch
- [ ] write error logs to tables in a log database
- [ ] asynchronously create database and tables as needed

### Tasks

- [ ] to be designed.
