### ISSUE TITLE
As a developer, I want to use git, so that I can easily deploy my dbt project

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#80]
### Acceptance Criteria

- [ ] codecommit origin automatically set up
- [ ] push to codecommit auto triggers deployment

### Tasks

- [ ] add cloudformation for setting up codecommit
- [ ] change code pipeline to use codecommit instead of s3 bucket

### Relates to

https://github.com/mytiki/lagoon/issues/73

**Comment by mike-audi** [comment]
codecommit was deprecated in jul. using s3 with separate versioned bucket (required for code build)
