### ISSUE TITLE
As a developer, I want to deploy to a sandbox environment, so that I can debug.

### ISSUE THREAD

**Issue by mike-audi** [mytiki/lagoon#81]
### Acceptance Criteria

- [ ] deploy sandbox code without disrupting production code
- [ ] run sandbox code on the same staging inputs
- [ ] save sandbox outputs without overwriting production outputs

### Tasks

- [ ] set up a dagster code location server for sandbox 
- [ ] write outputs to a different location than prd
- [ ] change where intermediaries are saved to avoid conflicts
- [ ] auto deploy to sandbox using codecommit
- [ ] auto deploy to production using codecommit

### Relates to

https://github.com/mytiki/lagoon/issues/80
